INSERT INTO public.tbl_faltas(
	id_falta, id_tipo_falta, incurrencia, orden, descripcion, borrado, reglamento)
	VALUES (26, 3, 1, 1, 'Reincidencia en cualquiera de las faltas graves.', FALSE, 2),
		(27, 3, 1, 1, 'Agredir físicamente a miembros de la Comunidad Universitaria', FALSE, 2),
		(28, 3, 1, 1, 'Desobediencia intencional y manifiesta a las autoridades de la UNAG, en asuntos de interés institucional con tendencia a la insubordinación;', FALSE, 2),
		(29, 3, 1, 1, 'Malversación de fondos de los estudiantes o de la institución', FALSE, 2),
		(30, 3, 1, 1, 'Sustracción de fondos y/o documentos', FALSE, 2),
		(31, 3, 1, 1, 'Falsificación de documentos para trámites legales propios de la UNAG', FALSE, 2),
		(32, 3, 1, 1, 'Tentativa o consumación de sabotajes al plantel o a los bienes de la institución', FALSE, 2),
		(33, 3, 1, 1, 'Allanamiento de las dependencias de la UNAG', FALSE, 2),
		(34, 3, 1, 1, 'Realización de actos que comprometan el nombre de la UNAG o de la Asociación de Estudiantes, en beneficio personal;', FALSE, 2),
		(35, 3, 1, 1, 'Perpetrar robos en perjuicio del personal, de los estudiantes o de la institución', FALSE, 2),
		(36, 3, 1, 1, 'Practicar dentro de la institución actos reñidos con la moral', FALSE, 2),
		(37, 3, 1, 1, 'Uso de las instalaciones de la UNAG, para realizar actividades ajenas a los fines de la institución, sin previa autorización de la Vicerrectoría de Vida Estudiantil, Dirección del Centro y la administración de la universidad.', FALSE, 2),
		(38, 3, 1, 1, 'Suspender labores para la realización de todo tipo de actividades sin previa autorización de la Rectoría o Dirección del Centro;', FALSE, 2),
		(39, 3, 1, 1, 'Incitar a los estudiantes a sublevarse contra las autoridades o contra las normas establecidas en pro del funcionamiento eficiente de la UNAG', FALSE, 2),
		(40, 3, 1, 1, 'Realizar actos que deterioren la imagen pública de la institución', FALSE, 2),
		(41, 3, 1, 1, 'Ejecutar actos, dentro o fuera de las instalaciones de la UNAG, que impliquen responsabilidad penal en cualquier grado;', FALSE, 2),
		(42, 3, 1, 1, 'Denigrar públicamente la institución dentro y fuera de la misma.', FALSE, 2),
		(43, 3, 1, 1, 'Lesionar o intentar lesionar la integridad física o psicológica, la libertad personal y sexual y los bienes de terceras personas, durante el desarrollo de actividades académicas, recreativas, deportivas, en la vivienda y comedores, o con ocasión de ellas, dentro y fuera de las instalaciones de la Universidad y sus dependencias.', FALSE, 2),
		(44, 3, 1, 1, 'Traficar o consumir dentro de la Universidad y sus dependencias (dormitorios, comedor, pasillos, áreas recreativas, etc.) o donde por la naturaleza de su actividad académica o institucional no se encontrare dentro de las mismas, cualquier tipo de drogas ilícitas o sustancias de abuso o ilícitas.', FALSE, 2),
		(45, 3, 1, 1, 'Hacerse suplantar o suplantar a otro en la realización de actividades que por su naturaleza debe ser realizada por el estudiante, ya sea prueba, examen, control de conocimientos o cualquier otra operación susceptible de ser evaluada.', FALSE, 2),
		(46, 3, 1, 1, 'Apoderarse por cualquier medio fraudulento o por abuso de confianza del contenido de una prueba, examen o control de conocimiento, en beneficio propio o ajeno, antes de su realización; o una vez realizada la evaluación procurar la sustracción, alteración o destrucción de fórmulas, cuestionarios, notas o calificaciones, etc., en beneficio propio o ajeno.', FALSE, 2),
		(47, 3, 1, 1, 'Realizar actos vandálicos o incitarlos, en perjuicio del patrimonio o de la buena marcha de la Institución.', FALSE, 2),
		(48, 3, 1, 1, 'Falsificar firmas de profesores o personal universitario o documentos de uso universitario.', FALSE, 2),
		(49, 3, 1, 1, 'Utilizar, con conocimiento de causa, documentos falsificados, para cualquier gestión universitaria administrativa, académica o de cualquier otra índole.', FALSE, 2),
		(50, 3, 1, 1, 'Suplantar a un profesional en la realización de la labor propia de éste, ya sea dentro o fuera de las instalaciones de la Universidad y sus dependencias, en actividades universitarias.', FALSE, 2),
		(51, 3, 1, 1, 'Mostrar conductas sexuales inadecuadas, violación o exhibicionismo, durante el desarrollo de actividades académicas e institucionales o con ocasión de ellas, dentro y fuera de las instalaciones de la Universidad y todas sus dependencias.', FALSE, 2),
		(52, 3, 1, 1, 'Plagiar, en todo o en parte, obras intelectuales de cualquier tipo.', FALSE, 2),
		(53, 3, 1, 1, 'Acosar a cualquier miembro de la comunidad universitaria', FALSE, 2);